### ISSUE TITLE
gws update fails when using https URLs

### ISSUE THREAD

**Issue by JohanSpaedtke** [emlun/gws2#12]
Cloning out new private repos configured to use a https URL fail with 

> folder/repoName:
>                               Cloning…
> Failed to clone project folder/repoName: remote authentication required but no callback set; class=Net (12)

and if they are configured with a git: url they fail with the following message

> folder/repoName:
>                               Cloning…
> Failed to clone project folder/repoName: authentication required but no callback set; class=Ssh (23)

`git clone` works fine for both URLs

**Comment by JohanSpaedtke** [comment]
A workaround is to simply configure the repo to use ssh instead which works just fine

**Comment by emlun** [comment]
Should be mostly fixed by #13. SSH seems to work great. I didn't find a reliable way to have git just prompt for an HTTPS password if needed, but with a little luck this might be enough to integrate nicely with OS keyrings. It might require setting a `git config --global credential.helper` first (see [gitcredentials(7)](https://git-scm.com/docs/gitcredentials)).

**Comment by JohanSpaedtke** [comment]
I’ll give it a try ASAP

**Comment by JohanSpaedtke** [comment]
On OSX it only seems to work after running
`git config --global credential.helper osxkeychain` 
and then using HTTPS URLs in `.projects.gws` 

Couldn't get it to work using SSH URLs. 

Didn't try any other credential.helper but seems like one is needed since if you don't specify one you'll never get prompted for credentials

**Comment by emlun** [comment]
Yeah, it seems like authenticated remotes aren't going to work at all without SSH or a credential helper.

> Couldn't get it to work using SSH URLs.

Are you using any SSH agent?

**Comment by emlun** [comment]
Merging #13 as good enough for now, let me know if you're still having problems. :slightly_smiling_face:
