### ISSUE TITLE
gws ff fails when there are merges

### ISSUE THREAD

**Issue by JohanSpaedtke** [emlun/gws2#7]
gws2 seems to get confused when there are merges. 

Running gws on the repo below results in 

> teamName/repoName
    master :                  Not in sync with origin/master

```
* 4513147 (origin/master, origin/HEAD) Updated even more things
*   52a956a fix baz
|\
| * b6b348b Updated quck
* | 10c44c7 fix qum
|/
*   220f593 fix qux
|\
| * da826c6 Update bam
* | 77de3ff fix bar
|/
* 35a8942 (HEAD -> master) foo
* 0039b21 Old stuff
```
The old bash version handles this just fine.

Output from git status
```
$ git status
On branch master
Your branch is behind 'origin/master' by 7 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
```
And running git pull works just fine
```
$git pull
Updating 35af942..4513247
Fast-forward
 README.md                  |  123 +++++++++++++++++-------------
 app/css/foo.css |  45 ++++++++++++++++-------------------
 app/js/bar.js       |  12 ++++++++++++++------
 3 files changed, 97 insertions(+), 68 deletions(-)
```

**Comment by emlun** [comment]
@JohanSpaedtke Does #8 fix it?

**Comment by JohanSpaedtke** [comment]
Well sort of but it seems only HEAD gets updated and not worktree. It handles the merge just fine but you end up with loads of modified files instead :)

**Comment by emlun** [comment]
Ok, try again now on the `merge-bug` branch (commit ac2eb543c9c9362a2a28d9f8f08fc84ac0148dce) :)

**Comment by JohanSpaedtke** [comment]
Works great :)
